/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface OnboarderShamanInterface extends utils.Interface {
  functions: {
    "amounts(uint256)": FunctionFragment;
    "baal()": FunctionFragment;
    "cuts(uint256)": FunctionFragment;
    "expiery()": FunctionFragment;
    "init(address,address,address,uint256,uint256,uint256,bool,address[],uint256[])": FunctionFragment;
    "lootPerUnit()": FunctionFragment;
    "onboarder()": FunctionFragment;
    "onboarder20(uint256)": FunctionFragment;
    "pricePerUnit()": FunctionFragment;
    "shares()": FunctionFragment;
    "token()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "amounts"
      | "baal"
      | "cuts"
      | "expiery"
      | "init"
      | "lootPerUnit"
      | "onboarder"
      | "onboarder20"
      | "pricePerUnit"
      | "shares"
      | "token"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "amounts",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "baal", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "cuts",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "expiery", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "init",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "lootPerUnit",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "onboarder", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "onboarder20",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "pricePerUnit",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "shares", values?: undefined): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;

  decodeFunctionResult(functionFragment: "amounts", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "baal", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cuts", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "expiery", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "init", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lootPerUnit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "onboarder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onboarder20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pricePerUnit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "shares", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;

  events: {
    "Initialized(uint8)": EventFragment;
    "YeetReceived(address,uint256,address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "YeetReceived"): EventFragment;
}

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface YeetReceivedEventObject {
  contributorAddress: string;
  amount: BigNumber;
  baal: string;
  lootToGive: BigNumber;
  lootToPlatform: BigNumber;
}
export type YeetReceivedEvent = TypedEvent<
  [string, BigNumber, string, BigNumber, BigNumber],
  YeetReceivedEventObject
>;

export type YeetReceivedEventFilter = TypedEventFilter<YeetReceivedEvent>;

export interface OnboarderShaman extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: OnboarderShamanInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    amounts(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    baal(overrides?: CallOverrides): Promise<[string]>;

    cuts(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    expiery(overrides?: CallOverrides): Promise<[BigNumber]>;

    init(
      _moloch: PromiseOrValue<string>,
      _token: PromiseOrValue<string>,
      _nftTemplate: PromiseOrValue<string>,
      _pricePer: PromiseOrValue<BigNumberish>,
      _unitPerUnit: PromiseOrValue<BigNumberish>,
      _expiery: PromiseOrValue<BigNumberish>,
      _shares: PromiseOrValue<boolean>,
      _cuts: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    lootPerUnit(overrides?: CallOverrides): Promise<[BigNumber]>;

    onboarder(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    onboarder20(
      _value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    pricePerUnit(overrides?: CallOverrides): Promise<[BigNumber]>;

    shares(overrides?: CallOverrides): Promise<[boolean]>;

    token(overrides?: CallOverrides): Promise<[string]>;
  };

  amounts(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  baal(overrides?: CallOverrides): Promise<string>;

  cuts(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  expiery(overrides?: CallOverrides): Promise<BigNumber>;

  init(
    _moloch: PromiseOrValue<string>,
    _token: PromiseOrValue<string>,
    _nftTemplate: PromiseOrValue<string>,
    _pricePer: PromiseOrValue<BigNumberish>,
    _unitPerUnit: PromiseOrValue<BigNumberish>,
    _expiery: PromiseOrValue<BigNumberish>,
    _shares: PromiseOrValue<boolean>,
    _cuts: PromiseOrValue<string>[],
    _amounts: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  lootPerUnit(overrides?: CallOverrides): Promise<BigNumber>;

  onboarder(
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  onboarder20(
    _value: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  pricePerUnit(overrides?: CallOverrides): Promise<BigNumber>;

  shares(overrides?: CallOverrides): Promise<boolean>;

  token(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    amounts(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    baal(overrides?: CallOverrides): Promise<string>;

    cuts(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    expiery(overrides?: CallOverrides): Promise<BigNumber>;

    init(
      _moloch: PromiseOrValue<string>,
      _token: PromiseOrValue<string>,
      _nftTemplate: PromiseOrValue<string>,
      _pricePer: PromiseOrValue<BigNumberish>,
      _unitPerUnit: PromiseOrValue<BigNumberish>,
      _expiery: PromiseOrValue<BigNumberish>,
      _shares: PromiseOrValue<boolean>,
      _cuts: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    lootPerUnit(overrides?: CallOverrides): Promise<BigNumber>;

    onboarder(overrides?: CallOverrides): Promise<void>;

    onboarder20(
      _value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    pricePerUnit(overrides?: CallOverrides): Promise<BigNumber>;

    shares(overrides?: CallOverrides): Promise<boolean>;

    token(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "YeetReceived(address,uint256,address,uint256,uint256)"(
      contributorAddress?: PromiseOrValue<string> | null,
      amount?: null,
      baal?: null,
      lootToGive?: null,
      lootToPlatform?: null
    ): YeetReceivedEventFilter;
    YeetReceived(
      contributorAddress?: PromiseOrValue<string> | null,
      amount?: null,
      baal?: null,
      lootToGive?: null,
      lootToPlatform?: null
    ): YeetReceivedEventFilter;
  };

  estimateGas: {
    amounts(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    baal(overrides?: CallOverrides): Promise<BigNumber>;

    cuts(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    expiery(overrides?: CallOverrides): Promise<BigNumber>;

    init(
      _moloch: PromiseOrValue<string>,
      _token: PromiseOrValue<string>,
      _nftTemplate: PromiseOrValue<string>,
      _pricePer: PromiseOrValue<BigNumberish>,
      _unitPerUnit: PromiseOrValue<BigNumberish>,
      _expiery: PromiseOrValue<BigNumberish>,
      _shares: PromiseOrValue<boolean>,
      _cuts: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    lootPerUnit(overrides?: CallOverrides): Promise<BigNumber>;

    onboarder(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    onboarder20(
      _value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    pricePerUnit(overrides?: CallOverrides): Promise<BigNumber>;

    shares(overrides?: CallOverrides): Promise<BigNumber>;

    token(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    amounts(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    baal(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    cuts(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    expiery(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    init(
      _moloch: PromiseOrValue<string>,
      _token: PromiseOrValue<string>,
      _nftTemplate: PromiseOrValue<string>,
      _pricePer: PromiseOrValue<BigNumberish>,
      _unitPerUnit: PromiseOrValue<BigNumberish>,
      _expiery: PromiseOrValue<BigNumberish>,
      _shares: PromiseOrValue<boolean>,
      _cuts: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    lootPerUnit(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    onboarder(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    onboarder20(
      _value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    pricePerUnit(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    shares(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    token(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
