/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ISPLITS__factory } from "./ISPLITS__factory";
export { PGRegistry__factory } from "./PGRegistry__factory";
