/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MemberRegistry__factory } from "./MemberRegistry__factory";
export { PGRegistry__factory } from "./PGRegistry__factory";
