/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as pgRegistrySol from "./PGRegistry.sol";
export { MemberRegistry__factory } from "./MemberRegistry__factory";
