/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MultiplyOnboarderShaman__factory } from "./MultiplyOnboarderShaman__factory";
export { MultiplyOnboarderShamanSummoner__factory } from "./MultiplyOnboarderShamanSummoner__factory";
