/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { StakeClaimShaman__factory } from "./StakeClaimShaman__factory";
export { StakeClaimShamanSummoner__factory } from "./StakeClaimShamanSummoner__factory";
