/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as didStampVcVerifierSol from "./DIDStampVCVerifier.sol";
export type { didStampVcVerifierSol };
import type * as diDpkhAdapterSol from "./DIDpkhAdapter.sol";
export type { diDpkhAdapterSol };
import type * as ididStampVcVerifierSol from "./IDIDStampVCVerifier.sol";
export type { ididStampVcVerifierSol };
import type * as vcVerifierSol from "./VCVerifier.sol";
export type { vcVerifierSol };
