/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Initializable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Initializable__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "IBAAL",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IBAAL__factory>;
    getContractFactory(
      name: "OnboarderShaman",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OnboarderShaman__factory>;
    getContractFactory(
      name: "OnboarderShamanSummoner",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OnboarderShamanSummoner__factory>;

    getContractAt(
      name: "Initializable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Initializable>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "IBAAL",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IBAAL>;
    getContractAt(
      name: "OnboarderShaman",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OnboarderShaman>;
    getContractAt(
      name: "OnboarderShamanSummoner",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OnboarderShamanSummoner>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
