/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IBAALTOKEN,
  IBAALTOKENInterface,
} from "../../../../contracts/tcr/SignalTCR.sol/IBAALTOKEN";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "snapshotId",
        type: "uint256",
      },
    ],
    name: "balanceOfAt",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getCurrentSnapshotId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IBAALTOKEN__factory {
  static readonly abi = _abi;
  static createInterface(): IBAALTOKENInterface {
    return new utils.Interface(_abi) as IBAALTOKENInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBAALTOKEN {
    return new Contract(address, _abi, signerOrProvider) as IBAALTOKEN;
  }
}
