/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ExampleManagerShaman } from "./ExampleManagerShaman";
export type { IBAAL } from "./IBAAL";
export type { IERC20 } from "./IERC20";
