/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface EthOnboarderShamanInterface extends utils.Interface {
  functions: {
    "PERC_POINTS()": FunctionFragment;
    "amounts(uint256)": FunctionFragment;
    "baal()": FunctionFragment;
    "cuts(uint256)": FunctionFragment;
    "expiery()": FunctionFragment;
    "init(address,uint256,uint256,uint256,bool,address[],uint256[])": FunctionFragment;
    "isShares()": FunctionFragment;
    "minTribute()": FunctionFragment;
    "multiply()": FunctionFragment;
    "onboarder()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "PERC_POINTS"
      | "amounts"
      | "baal"
      | "cuts"
      | "expiery"
      | "init"
      | "isShares"
      | "minTribute"
      | "multiply"
      | "onboarder"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "PERC_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "amounts",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "baal", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "cuts",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "expiery", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "init",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(functionFragment: "isShares", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "minTribute",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "multiply", values?: undefined): string;
  encodeFunctionData(functionFragment: "onboarder", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "PERC_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "amounts", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "baal", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cuts", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "expiery", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "init", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isShares", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "minTribute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "multiply", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "onboarder", data: BytesLike): Result;

  events: {
    "Initialized(uint8)": EventFragment;
    "ObReceived(address,uint256,uint256,uint256,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ObReceived"): EventFragment;
}

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface ObReceivedEventObject {
  contributorAddress: string;
  amount: BigNumber;
  totalFee: BigNumber;
  isShares: BigNumber;
  baal: string;
}
export type ObReceivedEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber, string],
  ObReceivedEventObject
>;

export type ObReceivedEventFilter = TypedEventFilter<ObReceivedEvent>;

export interface EthOnboarderShaman extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: EthOnboarderShamanInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    PERC_POINTS(overrides?: CallOverrides): Promise<[BigNumber]>;

    amounts(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    baal(overrides?: CallOverrides): Promise<[string]>;

    cuts(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    expiery(overrides?: CallOverrides): Promise<[BigNumber]>;

    init(
      _moloch: PromiseOrValue<string>,
      _expiery: PromiseOrValue<BigNumberish>,
      _multiply: PromiseOrValue<BigNumberish>,
      _minTribute: PromiseOrValue<BigNumberish>,
      _isShares: PromiseOrValue<boolean>,
      _cuts: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isShares(overrides?: CallOverrides): Promise<[boolean]>;

    minTribute(overrides?: CallOverrides): Promise<[BigNumber]>;

    multiply(overrides?: CallOverrides): Promise<[BigNumber]>;

    onboarder(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  PERC_POINTS(overrides?: CallOverrides): Promise<BigNumber>;

  amounts(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  baal(overrides?: CallOverrides): Promise<string>;

  cuts(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  expiery(overrides?: CallOverrides): Promise<BigNumber>;

  init(
    _moloch: PromiseOrValue<string>,
    _expiery: PromiseOrValue<BigNumberish>,
    _multiply: PromiseOrValue<BigNumberish>,
    _minTribute: PromiseOrValue<BigNumberish>,
    _isShares: PromiseOrValue<boolean>,
    _cuts: PromiseOrValue<string>[],
    _amounts: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isShares(overrides?: CallOverrides): Promise<boolean>;

  minTribute(overrides?: CallOverrides): Promise<BigNumber>;

  multiply(overrides?: CallOverrides): Promise<BigNumber>;

  onboarder(
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    PERC_POINTS(overrides?: CallOverrides): Promise<BigNumber>;

    amounts(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    baal(overrides?: CallOverrides): Promise<string>;

    cuts(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    expiery(overrides?: CallOverrides): Promise<BigNumber>;

    init(
      _moloch: PromiseOrValue<string>,
      _expiery: PromiseOrValue<BigNumberish>,
      _multiply: PromiseOrValue<BigNumberish>,
      _minTribute: PromiseOrValue<BigNumberish>,
      _isShares: PromiseOrValue<boolean>,
      _cuts: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    isShares(overrides?: CallOverrides): Promise<boolean>;

    minTribute(overrides?: CallOverrides): Promise<BigNumber>;

    multiply(overrides?: CallOverrides): Promise<BigNumber>;

    onboarder(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "ObReceived(address,uint256,uint256,uint256,address)"(
      contributorAddress?: PromiseOrValue<string> | null,
      amount?: null,
      totalFee?: null,
      isShares?: null,
      baal?: null
    ): ObReceivedEventFilter;
    ObReceived(
      contributorAddress?: PromiseOrValue<string> | null,
      amount?: null,
      totalFee?: null,
      isShares?: null,
      baal?: null
    ): ObReceivedEventFilter;
  };

  estimateGas: {
    PERC_POINTS(overrides?: CallOverrides): Promise<BigNumber>;

    amounts(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    baal(overrides?: CallOverrides): Promise<BigNumber>;

    cuts(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    expiery(overrides?: CallOverrides): Promise<BigNumber>;

    init(
      _moloch: PromiseOrValue<string>,
      _expiery: PromiseOrValue<BigNumberish>,
      _multiply: PromiseOrValue<BigNumberish>,
      _minTribute: PromiseOrValue<BigNumberish>,
      _isShares: PromiseOrValue<boolean>,
      _cuts: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isShares(overrides?: CallOverrides): Promise<BigNumber>;

    minTribute(overrides?: CallOverrides): Promise<BigNumber>;

    multiply(overrides?: CallOverrides): Promise<BigNumber>;

    onboarder(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    PERC_POINTS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    amounts(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    baal(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    cuts(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    expiery(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    init(
      _moloch: PromiseOrValue<string>,
      _expiery: PromiseOrValue<BigNumberish>,
      _multiply: PromiseOrValue<BigNumberish>,
      _minTribute: PromiseOrValue<BigNumberish>,
      _isShares: PromiseOrValue<boolean>,
      _cuts: PromiseOrValue<string>[],
      _amounts: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isShares(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    minTribute(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    multiply(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    onboarder(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
