/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EthOnboarderShaman } from "./EthOnboarderShaman";
export type { EthOnboarderShamanSummoner } from "./EthOnboarderShamanSummoner";
