/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockSplits__factory } from "./MockSplits__factory";
export { MyToken__factory } from "./MyToken__factory";
