/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IAdminShaman,
  IAdminShamanInterface,
} from "../../../../../../contracts/fixtures/Baal/contracts/interfaces/IAdminShaman";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "shaman",
        type: "address",
      },
    ],
    name: "isAdmin",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "pauseShares",
        type: "bool",
      },
      {
        internalType: "bool",
        name: "pauseLoot",
        type: "bool",
      },
    ],
    name: "setAdminConfig",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IAdminShaman__factory {
  static readonly abi = _abi;
  static createInterface(): IAdminShamanInterface {
    return new utils.Interface(_abi) as IAdminShamanInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAdminShaman {
    return new Contract(address, _abi, signerOrProvider) as IAdminShaman;
  }
}
