/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface SecondsUpdaterInterface extends utils.Interface {
  functions: {
    "registry()": FunctionFragment;
    "update()": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "registry" | "update"): FunctionFragment;

  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(functionFragment: "update", values?: undefined): string;

  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "update", data: BytesLike): Result;

  events: {
    "UpdateMemberActivity(address,uint32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "UpdateMemberActivity"): EventFragment;
}

export interface UpdateMemberActivityEventObject {
  member: string;
  newActivity: number;
}
export type UpdateMemberActivityEvent = TypedEvent<
  [string, number],
  UpdateMemberActivityEventObject
>;

export type UpdateMemberActivityEventFilter =
  TypedEventFilter<UpdateMemberActivityEvent>;

export interface SecondsUpdater extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SecondsUpdaterInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    registry(overrides?: CallOverrides): Promise<[string]>;

    update(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  registry(overrides?: CallOverrides): Promise<string>;

  update(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    registry(overrides?: CallOverrides): Promise<string>;

    update(overrides?: CallOverrides): Promise<number>;
  };

  filters: {
    "UpdateMemberActivity(address,uint32)"(
      member?: null,
      newActivity?: null
    ): UpdateMemberActivityEventFilter;
    UpdateMemberActivity(
      member?: null,
      newActivity?: null
    ): UpdateMemberActivityEventFilter;
  };

  estimateGas: {
    registry(overrides?: CallOverrides): Promise<BigNumber>;

    update(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    registry(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    update(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
