/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface CheckInSummonerInterface extends utils.Interface {
  functions: {
    "summon(address,bool,uint256,uint256,uint16)": FunctionFragment;
    "template()": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "summon" | "template"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "summon",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<boolean>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(functionFragment: "template", values?: undefined): string;

  decodeFunctionResult(functionFragment: "summon", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "template", data: BytesLike): Result;

  events: {
    "CheckInSummonComplete(address,address,bool,uint256,uint256,uint16)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CheckInSummonComplete"): EventFragment;
}

export interface CheckInSummonCompleteEventObject {
  baal: string;
  checkIn: string;
  sharesOrLoot: boolean;
  sharesPerMinute: BigNumber;
  checkInInterval: BigNumber;
  maxMinutesClaimable: number;
}
export type CheckInSummonCompleteEvent = TypedEvent<
  [string, string, boolean, BigNumber, BigNumber, number],
  CheckInSummonCompleteEventObject
>;

export type CheckInSummonCompleteEventFilter =
  TypedEventFilter<CheckInSummonCompleteEvent>;

export interface CheckInSummoner extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CheckInSummonerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    summon(
      _baal: PromiseOrValue<string>,
      _sharesOrLoot: PromiseOrValue<boolean>,
      _sharesPerMinute: PromiseOrValue<BigNumberish>,
      _checkInInterval: PromiseOrValue<BigNumberish>,
      _maxMinutesClaimable: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    template(overrides?: CallOverrides): Promise<[string]>;
  };

  summon(
    _baal: PromiseOrValue<string>,
    _sharesOrLoot: PromiseOrValue<boolean>,
    _sharesPerMinute: PromiseOrValue<BigNumberish>,
    _checkInInterval: PromiseOrValue<BigNumberish>,
    _maxMinutesClaimable: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  template(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    summon(
      _baal: PromiseOrValue<string>,
      _sharesOrLoot: PromiseOrValue<boolean>,
      _sharesPerMinute: PromiseOrValue<BigNumberish>,
      _checkInInterval: PromiseOrValue<BigNumberish>,
      _maxMinutesClaimable: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    template(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "CheckInSummonComplete(address,address,bool,uint256,uint256,uint16)"(
      baal?: PromiseOrValue<string> | null,
      checkIn?: null,
      sharesOrLoot?: null,
      sharesPerMinute?: null,
      checkInInterval?: null,
      maxMinutesClaimable?: null
    ): CheckInSummonCompleteEventFilter;
    CheckInSummonComplete(
      baal?: PromiseOrValue<string> | null,
      checkIn?: null,
      sharesOrLoot?: null,
      sharesPerMinute?: null,
      checkInInterval?: null,
      maxMinutesClaimable?: null
    ): CheckInSummonCompleteEventFilter;
  };

  estimateGas: {
    summon(
      _baal: PromiseOrValue<string>,
      _sharesOrLoot: PromiseOrValue<boolean>,
      _sharesPerMinute: PromiseOrValue<BigNumberish>,
      _checkInInterval: PromiseOrValue<BigNumberish>,
      _maxMinutesClaimable: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    template(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    summon(
      _baal: PromiseOrValue<string>,
      _sharesOrLoot: PromiseOrValue<boolean>,
      _sharesPerMinute: PromiseOrValue<BigNumberish>,
      _checkInInterval: PromiseOrValue<BigNumberish>,
      _maxMinutesClaimable: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    template(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
