/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface CheckInShamanInterface extends utils.Interface {
  functions: {
    "baal()": FunctionFragment;
    "checkInInterval()": FunctionFragment;
    "claim(uint32,string)": FunctionFragment;
    "init(address,bool,uint256,uint256)": FunctionFragment;
    "sharesOrLoot()": FunctionFragment;
    "sharesPerSecond()": FunctionFragment;
    "timeLedger(address)": FunctionFragment;
    "token()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "baal"
      | "checkInInterval"
      | "claim"
      | "init"
      | "sharesOrLoot"
      | "sharesPerSecond"
      | "timeLedger"
      | "token"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "baal", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "checkInInterval",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claim",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "init",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<boolean>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "sharesOrLoot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sharesPerSecond",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "timeLedger",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;

  decodeFunctionResult(functionFragment: "baal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkInInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "init", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sharesOrLoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sharesPerSecond",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "timeLedger", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;

  events: {
    "Claim(address,uint256,uint256,uint32,string)": EventFragment;
    "Initialized(uint8)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Claim"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
}

export interface ClaimEventObject {
  account: string;
  timestamp: BigNumber;
  tokenAmountClaimed: BigNumber;
  secondsWorked: number;
  metadata: string;
}
export type ClaimEvent = TypedEvent<
  [string, BigNumber, BigNumber, number, string],
  ClaimEventObject
>;

export type ClaimEventFilter = TypedEventFilter<ClaimEvent>;

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface CheckInShaman extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CheckInShamanInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    baal(overrides?: CallOverrides): Promise<[string]>;

    checkInInterval(overrides?: CallOverrides): Promise<[BigNumber]>;

    claim(
      _secondsWorked: PromiseOrValue<BigNumberish>,
      _metadata: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    init(
      _baal: PromiseOrValue<string>,
      _sharesOrLoot: PromiseOrValue<boolean>,
      _sharesPerSecond: PromiseOrValue<BigNumberish>,
      _checkInInterval: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    sharesOrLoot(overrides?: CallOverrides): Promise<[boolean]>;

    sharesPerSecond(overrides?: CallOverrides): Promise<[BigNumber]>;

    timeLedger(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    token(overrides?: CallOverrides): Promise<[string]>;
  };

  baal(overrides?: CallOverrides): Promise<string>;

  checkInInterval(overrides?: CallOverrides): Promise<BigNumber>;

  claim(
    _secondsWorked: PromiseOrValue<BigNumberish>,
    _metadata: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  init(
    _baal: PromiseOrValue<string>,
    _sharesOrLoot: PromiseOrValue<boolean>,
    _sharesPerSecond: PromiseOrValue<BigNumberish>,
    _checkInInterval: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  sharesOrLoot(overrides?: CallOverrides): Promise<boolean>;

  sharesPerSecond(overrides?: CallOverrides): Promise<BigNumber>;

  timeLedger(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  token(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    baal(overrides?: CallOverrides): Promise<string>;

    checkInInterval(overrides?: CallOverrides): Promise<BigNumber>;

    claim(
      _secondsWorked: PromiseOrValue<BigNumberish>,
      _metadata: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    init(
      _baal: PromiseOrValue<string>,
      _sharesOrLoot: PromiseOrValue<boolean>,
      _sharesPerSecond: PromiseOrValue<BigNumberish>,
      _checkInInterval: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    sharesOrLoot(overrides?: CallOverrides): Promise<boolean>;

    sharesPerSecond(overrides?: CallOverrides): Promise<BigNumber>;

    timeLedger(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    token(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "Claim(address,uint256,uint256,uint32,string)"(
      account?: null,
      timestamp?: null,
      tokenAmountClaimed?: null,
      secondsWorked?: null,
      metadata?: null
    ): ClaimEventFilter;
    Claim(
      account?: null,
      timestamp?: null,
      tokenAmountClaimed?: null,
      secondsWorked?: null,
      metadata?: null
    ): ClaimEventFilter;

    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;
  };

  estimateGas: {
    baal(overrides?: CallOverrides): Promise<BigNumber>;

    checkInInterval(overrides?: CallOverrides): Promise<BigNumber>;

    claim(
      _secondsWorked: PromiseOrValue<BigNumberish>,
      _metadata: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    init(
      _baal: PromiseOrValue<string>,
      _sharesOrLoot: PromiseOrValue<boolean>,
      _sharesPerSecond: PromiseOrValue<BigNumberish>,
      _checkInInterval: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    sharesOrLoot(overrides?: CallOverrides): Promise<BigNumber>;

    sharesPerSecond(overrides?: CallOverrides): Promise<BigNumber>;

    timeLedger(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    token(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    baal(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    checkInInterval(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    claim(
      _secondsWorked: PromiseOrValue<BigNumberish>,
      _metadata: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    init(
      _baal: PromiseOrValue<string>,
      _sharesOrLoot: PromiseOrValue<boolean>,
      _sharesPerSecond: PromiseOrValue<BigNumberish>,
      _checkInInterval: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    sharesOrLoot(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    sharesPerSecond(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    timeLedger(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    token(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
