/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as ethOnboarderSol from "./EthOnboarder.sol";
export * as simpleOnboarderSol from "./SimpleOnboarder.sol";
